### Create a 3×3 tensor or array containing the numbers from 1 to 9. Double it. Select the bottom-right four numbers.

#### Create the tensor

In [54]:
import torch


tensor_2d = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

tensor_2d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### Double it

In [55]:
tensor_2d = tensor_2d * 2

tensor_2d

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

#### Select bottom 4 numbers

In [59]:
tensor_2d.view(-1)[-4:]

tensor([12, 14, 16, 18])

### Create a function that, if passed two arguments [1,2,3,4] and 'abcd', returns [(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]. What is special about that output data structure?

In [63]:
from typing import List, Tuple, TypeVar

T = TypeVar("T")
K = TypeVar("K")



def zip_me(one: List[T], two: List[K]) -> List[Tuple[T,K]]:
    return list(zip(one, two))

one = [1,2,3,4]
two = ['a', 'b', 'c', 'd']

zip_me(one, two)

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]